export const ingredientsList = [{
            name: 'patate',
            image: 'https://image.shutterstock.com/image-photo/young-potato-isolated-on-white-260nw-1029398878.jpg',
            ratio: 30,
            rarity: 'commun',
        },
        {
            name: 'patate_douce',
            image: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bienmanger.com%2F1F34161_Patate_Douce_Bio.html&psig=AOvVaw2hWsLeDrPwKMbnUFuSxrdo&ust=1605884596777000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCq9cvwju0CFQAAAAAdAAAAABAD',
            ratio: 100,
            rarity: 'commun',

        },
        {
            name: 'frite',
            image: 'https://cdn2.webmanagercenter.com/di/wp-content/uploads/2014/09/fritte.jpg',
            ratio: 30,
            rarity: 'commun',
        },
        {
            name: 'poulet',
            image: 'https://svgsilh.com/svg/306299.svg',
            ratio: 100,
            rarity: 'rare',
        },
        {
            name: 'aubergine',
            image: 'https://www.biendecheznous.be/sites/default/files/ps_image/istock_aubergine.jpg',
            ratio: 30,
            rarity: 'rare',
        },
        {
            name: 'chèvre',
            image: 'https://svgsilh.com/svg/306299.svg',
            ratio: 30,
            rarity: 'rare',
        },
        {
            name: 'glace',
            image: 'https://www.laboutiquedeschefs.com/media/images/products/w-524-h-524-zc-2-preparation-mix-glace-yoggy-par-6x1-l-2-1521740425.jpg',
            ratio: 100,
            rarity: 'uncommun',
        },
        {
            name: 'haricot',
            image: 'https://img.cuisineaz.com/660x660/2017-03-23/i124155-haricots-verts-blanchis.jpeg',
            ratio: 30,
            rarity: 'uncommun',
        },
        {
            name: 'pomme',
            image: 'https://img-3.journaldesfemmes.fr/MCx4w7IOSyAvoIsvwADMRHU5mz0=/910x607/smart/899c9ccb1d6f4bfcbb2fdfed9d11c970/ccmcms-jdf/10662634.jpg',
            ratio: 30,
            rarity: 'uncommun',
        },